libgpg-error: fix src/gen-lock-obj.sh and src/gen-lock-obj-test.sh impurity
While playing around a bunch of stuff on Alpine
with Nix installed side-by-side I've hit build
error while cross compiling armv7 on x86_64:

> ./gpg-error.h:1129:33: error: unknown type name 'gpgrt_lock_t'; did you mean 'gpgrt_off_t'?
>  1129 | gpg_err_code_t gpgrt_lock_init (gpgrt_lock_t *lockhd);
>       |                                 ^~~~~~~~~~~~
>       |                                 gpgrt_off_t

Turned out some of the shebangs were not fixed up
by the default logic. Actual failure was in the
script failing silently earlier in the build log:

> checking for armv7l-unknown-linux-gnueabihf-objdump... (cached) armv7l-unknown-linux-gnueabihf-objdump
> ./configure: line 20057: ./src/gen-lock-obj.sh: cannot execute: required file not found

After fixing that bit in postPatch I later hit
another missing shebang fix:

> Confirm gpg-error-config works... /nix/store/5l50g7kzj7v0rdhshld1vx46rf2k5lf9-bash-5.2p26/bin/bash: line 1: ./gpg-error-config-test.sh: cannot execute: required file not found

The first script seems to not be caught by the
default shebang patcher. The second one is
generated after ./configure,
missing shebang patcher again.

Signed-off-by: Michal Kazior <michal@plume.com>